id: P1660F4B9
initial_creation_type: input
source_metadata:
  title: Bodhicitta Series
  language: pt
  description: Texts on the subject of bodhicitta (byang chub sems), which (on the
    relative level, at least) is the compassionate wish to attain enlightenment for
    the sake of all living beings—and has been variously translated into English as
    'thought of enlightenment', 'awakening-mind', 'spirit of awakening', etc.
  volume:
    263e46211538424ca972ea050a5aa54e:
      title: Advice for Tenzin Jamchen
      parent: Advice
    0f52d2aab86248c2814f79b45b5cc44f:
      title: Bodhicitta Aspiration
      parent: Aspirations
    b50defb94b5840d796eb076452ae85cf:
      title: Aspiration to Generate Bodhicitta, Utterly Pure and Supreme
      parent: Aspirations
    409bbedd4b704ea2a6e7fa2c8587f56a:
      title: An Extensive Commentary on the Four Immeasurables
      parent: Commentaries
    8f635912001945369b129675b58d7c1b:
      title: A Brief Commentary on the Refuge & Bodhichitta Prayer known as Sangyé
        Chö Tsok Ma
      parent: Commentaries
    72d62190eca54a0abf81a047d53c9e06:
      title: An Essential Instruction on Refuge and Bodhichitta
      parent: Commentaries
    750295a2a9a646f6b21689cdd9e1d90c:
      title: How Our Supreme Teacher Generated Bodhicitta and Other Topics
      parent: History
    d797dc106d184ddb9f68c4fd0acdfc0c:
      title: Daily Confession (from the Vajrapañjara Tantra)
      parent: Practices
    159f8f80d7ea48aa9b4268500d53e487:
      title: The Ritual of the Bodhisattva Vow According to the Tradition of Patrul
        Rinpoche
      parent: Practices
    263e6adae98441199e722d3e47acc060:
      title: Verses of Refuge and Bodhicitta
      parent: Practices
    44cff216846549e8b28acb820441e117:
      title: The Three Noble Principles
      parent: Three Noble Principles
created_at: '2022-03-01T03:03:50.800259'
last_modified_at: '2022-03-01T03:03:50.800262'
